ecs_cluster="$ECS_CLUSTER"
aws_access_key_id = "$AWS_ACCESS"
aws_secret_access_key = "$AWS_SECRET"
aws_region = "$AWS_REGION"
max_instance_size = "$MAX_INSTANCE_SIZE"
min_instance_size = "$MIN_INSTANCE_SIZE"
desired_capacity = "$DESIRED_CAPACITY"